INSERT INTO MPA (NAME)
SELECT 'G'
WHERE NOT EXISTS(SELECT 1 From MPA WHERE NAME = 'G');
INSERT INTO MPA (NAME)
SELECT 'PG'
WHERE NOT EXISTS(SELECT 1 From MPA WHERE NAME = 'PG');
INSERT INTO MPA (NAME)
SELECT 'PG-13'
WHERE NOT EXISTS(SELECT 1 From MPA WHERE NAME = 'PG-13');
INSERT INTO MPA (NAME)
SELECT 'R'
WHERE NOT EXISTS(SELECT 1 From MPA WHERE NAME = 'R');
INSERT INTO MPA (NAME)
SELECT 'NC-17'
WHERE NOT EXISTS(SELECT 1 From MPA WHERE NAME = 'NC-17');
INSERT INTO GENRES (TITLE)
SELECT 'Комедия'
WHERE NOT EXISTS(SELECT 1 From GENRES WHERE TITLE = 'Комедия');
INSERT INTO GENRES (TITLE)
SELECT 'Драма'
WHERE NOT EXISTS(SELECT 1 From GENRES WHERE TITLE = 'Драма');
INSERT INTO GENRES (TITLE)
SELECT 'Мультфильм'
WHERE NOT EXISTS(SELECT 1 From GENRES WHERE TITLE = 'Мультфильм');
INSERT INTO GENRES (TITLE)
SELECT 'Триллер'
WHERE NOT EXISTS(SELECT 1 From GENRES WHERE TITLE = 'Триллер');
INSERT INTO GENRES (TITLE)
SELECT 'Документальный'
WHERE NOT EXISTS(SELECT 1 From GENRES WHERE TITLE = 'Документальный');
INSERT INTO GENRES (TITLE)
SELECT 'Боевик'
WHERE NOT EXISTS(SELECT 1 From GENRES WHERE TITLE = 'Боевик');
INSERT INTO STATUS (NAME)
SELECT 'IN_FRIENDS'
WHERE NOT EXISTS(SELECT 1 From STATUS WHERE NAME = 'IN_FRIENDS');
INSERT INTO STATUS (NAME)
SELECT 'SENT_REQUEST'
WHERE NOT EXISTS(SELECT 1 From STATUS WHERE NAME = 'SENT_REQUEST');