CREATE TABLE IF NOT EXISTS Users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar,
    login varchar,
    name varchar,
    birthday timestamp
);
CREATE TABLE IF NOT EXISTS Status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);
CREATE TABLE IF NOT EXISTS Friends (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    send_friend_user_id integer REFERENCES Users (id),
    status_id integer REFERENCES Status (id),
    get_friend_user_id integer REFERENCES Users (id)
);
CREATE TABLE IF NOT EXISTS Mpa (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar
);
CREATE TABLE IF NOT EXISTS Genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title varchar
);
CREATE TABLE IF NOT EXISTS Films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar,
    description varchar,
    release_date timestamp,
    duration integer,
    mpa integer REFERENCES Mpa (id)
);
CREATE TABLE IF NOT EXISTS Genre_of_film (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer REFERENCES Films (id),
    genre_id integer REFERENCES Genres (id)
);
CREATE TABLE IF NOT EXISTS Likes (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id integer REFERENCES Films (id),
    user_id integer REFERENCES Users (id)
);

